language: perl
perl:
   - "5.18"
matrix:
   include:
      - perl: 5.18
        env: COVERAGE=1
   allow_failures:
      - perl: "blead"
        sudo: true
os:
   - linux
addons:
   apt:
      packages:
         - freeglut3-dev
         - xutils-dev
         - libxi-dev
         - libxxf86vm-dev
         - x11proto-xf86vidmode-dev
         - mesa-utils
         - xvfb
         - libgl1-mesa-dri
         - libglapi-mesa
         - libosmesa6
before_install:
   - if [ "${TRAVIS_OS_NAME}" = "linux" ]; then export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start; fi
   - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
   - source ~/travis-perl-helpers/init
   - build-perl
   - perl -V
   - build-dist
   - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
   - cpan-install --deps
before_script:
#- coverage-setup
script:
   - prove -bv t
after_success:
#
